### ISSUE TITLE
Outils d’intégration continu Produits

### ISSUE THREAD

**Issue by franswap** [epsi-mspr-bloc-4-g4/api-produits#7]

**Comment by jul-fls** [comment]
La pipeline Build and Test pour le repo "api-produits" est en place avec le lancement des tests unitaires et le scan sonarqube.
Il ne reste que le déploiement automatique à gérer.

**Comment by jul-fls** [comment]
Le déploiement se fera via une stack docker compose globale au 4 micro services : 
- Api Gateway
- Api Clients
- Api Commandes
- Api Produits

Il n'y as donc pas lieu d'y avoir une stack docker compose par micro service étant donné qu'il s'agit d'un déploiement global et unifié.
